#include <assert.h>
#include <dirent.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "../include/read_cfg.h"
#include "../include/entry.h"

char sep = '/';

char *find_config(){
	char *home = getenv("HOME");
	char *path = malloc(sizeof(char) * BUF_LEN);
	char choices[2][BUF_LEN];
	int check_count = 2;
	int i;

	sprintf(choices[0], "%s%c.config%cterminal-media-launcher%cconfig.lua", home, sep, sep, sep);
	sprintf(choices[1], "%s%c.terminal-media-launcher%cconfig.lua", home, sep, sep);

	for(i = 0; i < check_count; i++){
		strcpy(path, choices[i]);
		printf("Checking for config at %s: ", choices[i]);
		if(access(path, R_OK) == 0){
			printf("Using config \"%s\"\n\n", path);
			return path;
		}
		else printf("File does not exist\n");
	}

	mkconfig_wizard(choices[0]);
	strcpy(path, choices[0]);
	return path;
}

void mkconfig_wizard(char *path){
	char input;
	FILE *fp;

	char *home = getenv("HOME");

	printf("\nNo configuration file found. Auto-generate one now at \"%s\"? [Y/n] ", path);
	fflush(stdout);
	scanf(" %c", &input);

	if(input == 'n'){
		printf("Configuration will not be auto-generated\n");
		refer_to_doc();
		exit(0);
		
	}

	printf("Generating configuration file at \"%s\"...\n", path);

	//ensure directories have been created
	if(home == NULL){
		printf("Failed: HOME is NULL\n");
		exit(1);
	}

	sprintf(path, "%s%c.config%c", home, sep, sep);
	mkdir(path, 0755);

	sprintf(path, "%s%c.config%cterminal-media-launcher%c", home, sep, sep, sep);
	mkdir(path, 0755);

	sprintf(path, "%s%c.config%cterminal-media-launcher%cconfig.lua", home, sep, sep, sep);

	//open file for writing, make sure non-NULL
	fp = fopen(path, "w");
	if(fp == NULL){
		printf("Failed: \"%s\" could not be open for writing\n", path);
		exit(1);
	}

	fprintf(fp, 
		"-- This file was auto-generated by terminal-media-launcher. See docs/terminal-media-launcher-config.md or terminal-media-launcher-config(5) for documentation\n"
		"-- The default launcher is set to \"xdg-open\" which will open files based on the relevant default application set through xdg\n\n"
		"local lfs = require \"lfs\"\n"
		"\n"
		"local function addGroup(name, launcher, flags)\n"
		"	assert(type(name) == \"string\")\n"
		"\n"
		"    -- create Groups table if needed\n"
		"    if Groups == nil then\n"
		"        Groups = {}\n"
		"    end\n"
		"\n"
		"    local new_group = {}\n"
		"    new_group.name = name\n"
		"	new_group.Entries = {}\n"
		"    if launcher ~= nil then\n"
		"        new_group.Launcher = launcher\n"
		"    end\n"
		"    if flags ~= nil then\n"
		"        new_group.Flags = flags\n"
		"    end\n"
		"\n"
		"    table.insert(Groups, new_group)\n"
		"    return new_group\n"
		"end\n"
		"\n"
		"local function addEntries(parentGroup, startDir, filePattern, recursive)\n"
		"	-- recursive arg is a boolean for whether or not to descend into subdirectories (false by default)\n"
		"	assert(type(parentGroup) == \"table\")\n"
		"	assert(type(parentGroup.Entries) == \"table\")\n"
		"	assert(type(startDir) == \"string\")\n"
		"	assert(type(filePattern) == \"string\")\n"
		"\n"
		"	for file in lfs.dir(startDir) do\n"
		"		local fullFilePath = startDir .. \"/\" .. file\n"
		"		if file ~= \".\" and file ~= \"..\" then\n"
		"			-- descend into subdirectory if recursive is set to true\n"
		"			if lfs.attributes(fullFilePath).mode == \"directory\" and recursive == true then\n"
		"				addEntries(parentGroup, fullFilePath, filePattern, recursive)\n"
		"			elseif lfs.attributes(fullFilePath).mode == \"file\" then\n"
		"				if string.match(file, filePattern) then\n"
		"					table.insert(parentGroup.Entries, {\n"
		"						name = file,\n"
		"						path = fullFilePath\n"
		"					})\n"
		"				end\n"
		"			end\n"
		"		end\n"
		"	end\n"
		"end\n"
		"\n"
		"local music = addGroup(\"Music\", \"xdg-open\")\n"
		"addEntries(music, os.getenv(\"HOME\") .. \"/Music\", \".*\", true)\n"
		"\n"
		"local pictures = addGroup(\"Pictures\", \"xdg-open\")\n"
		"addEntries(pictures, os.getenv(\"HOME\") .. \"/Pictures\", \".*\", true)\n"
		"\n"
		"local videos = addGroup(\"Videos\", \"xdg-open\")\n"
		"addEntries(videos, os.getenv(\"HOME\") .. \"/Videos\", \".*\", true)\n");

	fclose(fp);
	printf("done\nIt is highly recommended to further tweak the configuration file! [press any key to continue]");
	fflush(stdout);
	getchar();
	getchar();

	return;
}
